DECLARE @MigrationNumber int = 5;
DECLARE @MigrationName varchar(255) = '005_Add_Comments_And_LogWork.sql'; 

IF(NOT EXISTS(SELECT * FROM Ziro_DbMigrations WHERE MigrationNumer >= @MigrationNumber))
BEGIN
	CREATE TABLE Ziro_Comment (Id UNIQUEIDENTIFIER NOT NULL, Text NVARCHAR(4000) NULL, [Date] DATETIME2 NOT NULL, AuthorId UNIQUEIDENTIFIER NULL, TaskId UNIQUEIDENTIFIER NULL, PRIMARY KEY (Id)) 
	CREATE TABLE Ziro_LogWork (Id UNIQUEIDENTIFIER NOT NULL, Text NVARCHAR(4000) NULL, SpentTimeHours FLOAT(53) NOT NULL, Date DATETIME2 NOT NULL, AuthorId UNIQUEIDENTIFIER NULL, TaskId UNIQUEIDENTIFIER NULL, PRIMARY KEY (Id)) 
	
	ALTER TABLE Ziro_Comment ADD CONSTRAINT FK_E1D32329 FOREIGN KEY (AuthorId) REFERENCES Ziro_User 
	ALTER TABLE Ziro_Comment ADD CONSTRAINT FK_4BEF0DEF FOREIGN KEY (TaskId) REFERENCES Ziro_Task 
	ALTER TABLE Ziro_LogWork ADD CONSTRAINT FK_68853563 FOREIGN KEY (AuthorId) REFERENCES Ziro_User 
	ALTER TABLE Ziro_LogWork ADD CONSTRAINT FK_DBE31971 FOREIGN KEY (TaskId) REFERENCES Ziro_Task 

	-- update dbVersion
	INSERT INTO Ziro_DbMigrations VALUES(@MigrationNumber, @MigrationName)
END
ELSE 
      PRINT N'Migration ' + @MigrationName + N' was skipped';